### ISSUE TITLE
Camera manager should not take pictures at night

### ISSUE THREAD

**Issue by mtlynch** [JeetShetty/GreenPiThumb#118]
We should integrate with the light sensor to detect when it's too dark to take a photo

**Comment by JeetShetty** [comment]
Can I just add the light sensor to the ```_CameraPollWorker``` class? Are there any issues with the light sensor being read too frequently?

**Comment by mtlynch** [comment]
Yeah that should work. I don't think there's much of a cost to reading the light sensor a lot.
