### ISSUE TITLE
Implement sleep window parser

### ISSUE THREAD

**Issue by mtlynch** [JeetShetty/GreenPiThumb#49]
`pump_scheduler.py` relies on having a list of sleep windows where the pump doesn't run. We need to have some way for the user to actually communicate this.

I think the easiest would be a command line flag, like the user does:

```shell
python greenpithumb.py \
  --sleep_windows "12:30-1:30,22:00-6:00,8:00-8:01"
```

We could alternatively do it in a config file, but I find config files make things harder to just copy/paste easily.

**Comment by JeetShetty** [comment]
I'm not sure how this works. How do we read in what the user is supplying?

**Comment by mtlynch** [comment]
Oh, it's a command line flag. We're doing something really similar already with `--config_file` so when we run GreenPiThumb with

```shell
python greenpithumb.py \
  --config_file "C:\projects\greenpithumb\config.ini"
```

When we're in the `main` function in [greenpithumb.py](https://github.com/JeetShetty/GreenPiThumb/blob/master/greenpithumb/greenpithumb.py), `args.config_file` will be set to `"C:\projects\greenpithumb\config.ini"`.

So if we want to add a new flag, we can do it through `parser.add_argument` at the bottom of greenpithumb.py and then it will be available in the `args` parameter in `main` like `args.config_file`.
