### ISSUE TITLE
Add GPIO.setmode

### ISSUE THREAD

**Issue by JeetShetty** [JeetShetty/GreenPiThumb#54]
Seems to me that we want to use GPIO.BOARD, but you used GPIO.BCM in some of your code. I'm not clear on what each does, though.

**Comment by mtlynch** [comment]
`GPIO.BCM` matches the numbers printed on the [Raspberry Pi cobbler](http://a.co/234GrbU) we use and in Fritzing.

I think the upside of `GPIO.BOARD` is that it will work across Raspberry Pi versions, but I'd rather sacrifice that to eliminate the confusion of having to keep looking at [this diagram](http://www.raspberrypi-spy.co.uk/wp-content/uploads/2012/06/Raspberry-Pi-GPIO-Layout-Model-B-Plus-rotated-2700x900-1024x341.png) to map the board numbers to the board-independent numbers.
