### ISSUE TITLE
pi_io needs to be thread-safe

### ISSUE THREAD

**Issue by mtlynch** [JeetShetty/GreenPiThumb#83]
It's shared by two different threads, so it needs sane behavior when multiple threads try to close it and when threads try to call its normal methods after another thread has closed it.

**Comment by JeetShetty** [comment]
Shouldn't the main thread be the only calling ```close```?

**Comment by mtlynch** [comment]
>Shouldn't the main thread be the only one calling close?

Yeah that's true.
